{{- if .Values.azure }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: pple-masters-database-secretproviderclass
  namespace: "{{ .Release.Namespace }}"
spec:
  provider: azure
  secretObjects:
    - secretName: pple-masters-database-secret
      type: Opaque
      data:
      {{- range .Values.azure.secrets }}
        - objectName: {{ .name }}
          key: {{ .key }}
      {{- end }}
    - secretName: ingress-tls-csi-pple-masters-database
      type: kubernetes.io/tls
      data:
        - objectName: masters-database-pple-uva-nl
          key: tls.key
        - objectName: masters-database-pple-uva-nl
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.azure.clientId }}"
    keyvaultName: "{{ .Values.azure.keyvaultName }}"
    cloudName: AzurePublicCloud
    objects: |
      array:
      {{- range .Values.azure.secrets }}
        - |
          objectName: {{ .name }}
          objectType: secret
      {{- end }}
        - |
          objectName: masters-database-pple-uva-nl
          objectType: secret
    resourceGroup: "{{ .Values.azure.resourceGroup }}"
    subscriptionId: "{{ .Values.azure.subscriptionId }}"
    tenantId: "{{ .Values.azure.tenantId }}"
  {{- end }}