apiVersion: v1
kind: Service
metadata:
  name: pple-masters-database
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pple-masters-database
